Making better outputs
LadyNaggaga/training-tutorials pull request #103
Opened 2017-04-11 21:30 UTC by arynhuck

Closes issue #100 .
We changed how outputs are formatted so everything makes sense and feels like part of one tutorial.

2017-04-15 20:47 UTC, helmoski requested changes

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
> +Next, let's look at how to update records that are already in the database. For example, we might discover that one of our books was catelogged incorrectly. _Mrs Dalloway_ should be _To the Lighthous
catalogued

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
> +	book.PublicationYear = 1927;
Fix tabbing

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
> +Suppose you want to update an untracked entity. As long as the untracked entity has the same primary key as the record in the database, you can accomplish this using the `DbSet`'s `Update` method. In
The updated sentence is hard to follow

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
> +		Genre = "Literary",
Fix tabbing

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/count-method/Program.cs
> +            Console.WriteLine("Number of {0} {1} books: {2}", author.FirstName, author.LastName, numBooks);
Number of books by ____ _____: #

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +
Remove this newline

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +
Remove the whitespace on this line

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Checked out *by* Reader:

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-method/Program.cs
> +			Console.WriteLine("Included author with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.PublicationYear, book.Author.Fir
Fix tabbing

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-method/Program.cs
> +			Console.WriteLine("Included author with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.PublicationYear, book.Author.Fir
Use multiple `Console.WriteLine` statements instead of the newline characters. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +			Console.WriteLine("Book: {0}\n Author: {1} {2}", book.Title, book.Author.FirstName, book.Author.LastName);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author {0} {1}", author.FirstName, author.LastName);
Add a comma or colon after "author"

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Explicitly loaded the author's books -");
Use a colon instead

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/multiple-include-methods/Program.cs
> +			Console.WriteLine("Included author and checkout record(s) with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.Publicati
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author {0} {1}", author.FirstName, author.LastName);
Add comma or colon

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Used a query to find the book ");
Fix tabbing

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +
Remove newline

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +					Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +
Remove newline

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
Remove newline

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
"Book, _____, added to author, ____ ____"

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Add commas around author's name

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Use colon instead of dash

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +                Console.WriteLine("\nTitle: {0}\n Genre: {1}\n Publication Year: {2}", book.Title, book.Genre, book.PublicationYear);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
Remove extra newline

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +            Console.WriteLine("Original Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", book.Id, book.Title, book.Genre, book.PublicationYear);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +			Console.WriteLine("\nUpdated Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", book.Id, book.Title, book.Genre, book.PublicationYear);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +				Genre = "Literary",
You don't say you will also update genre in the text explaining the example

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +            Console.WriteLine("Updated Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", updatedBook.Id, updatedBook.Title, updatedBook.Genre, updatedBook.PublicationYear);
Use multiple `Console.WriteLine` statements instead of the newlines. It will make the code more readable.

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +			Console.WriteLine("Historical books in library -");
Fix tabbing

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +			Console.WriteLine("Historical books in library -");
Use colon instead of dash

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +            Console.WriteLine("Books in library -");
Use colon instead of dash

2017-04-15 20:47 UTC, helmoski commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +			foreach (Book book in books)
Fix tabbing

2017-04-15 23:32 UTC, deakgeek commented on content/efcore/getting-started/manipulating-entities.md
> +Next, let's look at how to update records that are already in the database. For example, we might discover that one of our books was catelogged incorrectly. _Mrs Dalloway_ should be _To the Lighthous
Done

2017-04-15 23:38 UTC, deakgeek commented on content/efcore/getting-started/manipulating-entities.md
> +Suppose you want to update an untracked entity. As long as the untracked entity has the same primary key as the record in the database, you can accomplish this using the `DbSet`'s `Update` method. In
Done

2017-04-15 23:40 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/count-method/Program.cs
> +            Console.WriteLine("Number of {0} {1} books: {2}", author.FirstName, author.LastName, numBooks);
Done

2017-04-15 23:44 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-15 23:46 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +
Done

2017-04-15 23:58 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +			Console.WriteLine("Book: {0}\n Author: {1} {2}", book.Title, book.Author.FirstName, book.Author.LastName);
Done

2017-04-15 23:59 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +
Done

2017-04-16 00:00 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-16 00:07 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-method/Program.cs
> +			Console.WriteLine("Included author with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.PublicationYear, book.Author.Fir
Done

2017-04-16 00:09 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author {0} {1}", author.FirstName, author.LastName);
Done

2017-04-16 00:10 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Explicitly loaded the author's books -");
Done

2017-04-16 00:14 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/multiple-include-methods/Program.cs
> +			Console.WriteLine("Included author and checkout record(s) with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.Publicati
Done

2017-04-16 00:15 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author {0} {1}", author.FirstName, author.LastName);
Done

2017-04-16 00:17 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +
Done

2017-04-16 00:19 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +					Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-16 00:28 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +
Done

2017-04-16 00:29 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Due Date: {0}\n Checked out from Reader: {1} {2}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"), checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName
Done

2017-04-16 00:30 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
Done

2017-04-16 00:34 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
I did change this one, but it does seem a little odd repeating the book title twice.

2017-04-16 00:35 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Done

2017-04-16 00:38 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
For our output design, we use dashes for the initial label or phrase, then colons for any following labels or if there is only a single one.

2017-04-16 00:38 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
Done

2017-04-16 00:42 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +                Console.WriteLine("\nTitle: {0}\n Genre: {1}\n Publication Year: {2}", book.Title, book.Genre, book.PublicationYear);
Done

2017-04-16 00:47 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +            Console.WriteLine("Original Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", book.Id, book.Title, book.Genre, book.PublicationYear);
Done

2017-04-16 00:47 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +			Console.WriteLine("\nUpdated Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", book.Id, book.Title, book.Genre, book.PublicationYear);
Done

2017-04-16 00:54 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +				Genre = "Literary",
Added to the sentence above. Done

2017-04-16 00:54 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +            Console.WriteLine("Updated Book -\n Id: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}", updatedBook.Id, updatedBook.Title, updatedBook.Genre, updatedBook.PublicationYear);
Done

2017-04-16 00:56 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +			Console.WriteLine("Historical books in library -");
Again, this was how we decided to handle the initial phrase.

2017-04-16 00:57 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +            Console.WriteLine("Books in library -");
Again, this was how we decided to handle the initial phrase.

2017-04-16 01:01 UTC, deakgeek commented on content/efcore/getting-started/manipulating-entities.md
> +	book.PublicationYear = 1927;
Done

2017-04-16 01:04 UTC, deakgeek commented on content/efcore/getting-started/manipulating-entities.md
> +		Genre = "Literary",
Done

2017-04-16 01:17 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-method/Program.cs
> +			Console.WriteLine("Included author with book - \nId: {0}\n Title: {1}\n Genre: {2}\n Publication Year: {3}\nAuthor: {4} {5}", book.Id, book.Title, book.Genre, book.PublicationYear, book.Author.Fir
Done

2017-04-16 01:19 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Used a query to find the book ");
Done

2017-04-16 01:20 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +			Console.WriteLine("Historical books in library -");
Done

2017-04-16 01:20 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +			foreach (Book book in books)
Done

2017-04-16 03:48 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
Remove the second `Console.WriteLine` that prints out the books info. It isn't necessary for this example.

2017-04-16 03:50 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
> +            Console.WriteLine("Title: {0}\n Genre: {1}\n Publication Year: {2}", addedBook.Title, addedBook.Genre, addedBook.PublicationYear);
Remove the second `Console.WriteLine` that prints out the books info. It isn't necessary for this example.

2017-04-16 03:50 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 03:51 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author {0} {1} with their book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 03:51 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
Remove the second `Console.WriteLine` that prints out the books info. It isn't necessary for this example.

2017-04-16 03:51 UTC, helmoski commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +			Console.WriteLine("Historical books in library -");
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 03:52 UTC, helmoski commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +            Console.WriteLine("Books in library -");
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 04:08 UTC, helmoski requested changes

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Checked out from Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Checked out *by* Reader:

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +			Console.WriteLine("Book: {0}", book.Title);
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Checked out from Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
I don't think the output for this example makes sense. How about the following:

Checkout Records for <`Book.Title`>:
<`CheckoutRecord.CheckoutDate`> - <`Reader.FirstName`> <`Reader.LastName`>

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +			Console.WriteLine("\nUpdated Book -");
Fix tabbing in this file

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +            Console.WriteLine("Original Book -");
I think something like, `~~ Original Book ~~` would make a better title.

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +				Genre = "Literary",
It doesn't seem to have been committed. The sentence hasn't changed. Also, the corresponding in-tutorial code doesn't adjust `Genre` either.

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +			{
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +            Console.WriteLine("Updated Book -");
Again, `~~ Updated Book ~~` would probably be more readable

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +            Console.WriteLine("Historical books in library -");
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +            Console.WriteLine("Books in library -");
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author \"{0} {1}\" with her book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Colons are used to introduce lists, not dashes:

- http://www.wheaton.edu/Academics/Services/Writing-Center/Writing-Resources/Semicolons-Colons-and-Dashes
- http://writingcenter.unc.edu/handouts/semi-colons-colons-and-dashes/
- https://www.pugetsound.edu/academics/academic-resources/cwlt/writing-advisor-schedule/writing-resources/colon-and-dashes/
- https://www.bethel.edu/undergrad/academics/support/colon-dash.pdf

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author \"{0} {1}\" with her book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +
Remove unnecessary newline

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +                    Console.WriteLine("Checked out by Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author: {0} {1}", author.FirstName, author.LastName);
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/multiple-include-methods/Program.cs
> +			Console.WriteLine("Included author and checkout record(s) with book -");
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author: {0} {1}", author.FirstName, author.LastName);
Fix tabbing

2017-04-16 04:08 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"));
Fix tabbing

2017-04-16 04:09 UTC, helmoski commented
Go through all the files and fix tabbing. Use **spaces** everywhere, not tabs.

2017-04-17 20:46 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/add-new-entity-to-existing/Program.cs
> +            Console.WriteLine("Title: {0}\n Genre: {1}\n Publication Year: {2}", addedBook.Title, addedBook.Genre, addedBook.PublicationYear);
Done

2017-04-17 20:48 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +			Console.WriteLine("Book: {0}", book.Title);
Done

2017-04-17 20:49 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Checked out from Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-17 20:55 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                Console.WriteLine("Checked out from Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-17 20:56 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +            Console.WriteLine("Original Book -");
Done

2017-04-17 20:57 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-entities/Program.cs
> +			Console.WriteLine("\nUpdated Book -");
Done

2017-04-17 20:59 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +			{
Done

2017-04-17 21:02 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/updating-untracked-entities/Program.cs
> +            Console.WriteLine("Updated Book -");
Done

2017-04-17 21:05 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/filtering-entities/Program.cs
> +            Console.WriteLine("Historical books in library -");
Done

2017-04-17 21:05 UTC, deakgeek commented on content/efcore/getting-started/samples/querying/loading-all-entities/Program.cs
> +            Console.WriteLine("Books in library -");
Done

2017-04-17 21:06 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +
Done

2017-04-17 21:07 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author \"{0} {1}\" with her book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Done

2017-04-17 21:09 UTC, deakgeek commented on content/efcore/getting-started/samples/manipulating-entities/adding-related-entities/Program.cs
> +			Console.WriteLine("We added the author \"{0} {1}\" with her book(s) -", addedAuthor.FirstName, addedAuthor.LastName);
Done

2017-04-17 21:11 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +                    Console.WriteLine("Checked out by Reader: {0} {1}", checkoutRecord.Reader.FirstName, checkoutRecord.Reader.LastName);
Done

2017-04-17 21:12 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/query-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author: {0} {1}", author.FirstName, author.LastName);
Done

2017-04-17 21:13 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/multiple-include-methods/Program.cs
> +			Console.WriteLine("Included author and checkout record(s) with book -");
Done

2017-04-17 21:14 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/load-method/Program.cs
> +			Console.WriteLine("Eagerly loaded author: {0} {1}", author.FirstName, author.LastName);
Done

2017-04-17 21:16 UTC, deakgeek commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +				Console.WriteLine("Due Date: {0}", checkoutRecord.DueDate.ToString("MMMM dd, yyyy"));
Done

2017-04-24 21:33 UTC, helmoski approved these changes

2017-04-24 21:33 UTC, merged