1 getting started readme
LadyNaggaga/training-tutorials pull request #15
Opened 2016-10-24 21:10 UTC by davidmikh

2016-10-24 23:53 UTC, rdahlman3 commented on content/efcore/getting-started/README.md
> +If you're a new to these topics, you can check out their tutorials. If you're only a little rusty, we'll remind you of the relevant aspects along the way.
Typo - remove the `a` in `If you're a new to these topics`

2016-10-25 01:31 UTC, helmoski requested changes
- [ ] Remove Author(s)
- [ ] Reorganize to match C# tutorial
  - [ ] Introducing EF Core chapter
  - [ ] Add table of contents to `content/efcore/getting-started/README.md`
- [ ] Some rewording and cutting out of content
- [ ] Remove unrecognized characters

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +by [The Raikes School](http://cse.unl.edu/raikes-school)
Update from Maria: Leave out the author(s) for now. We can add them later.

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +Entity Framework Core (EF Core) is a lightweight, extensible, and cross-platform version of Entity Framework. Entity Framework is an object-relational mapper (O/RM) that enables .NET developers to wo
![image](https://cloud.githubusercontent.com/assets/8516113/19667026/eaa34636-9a13-11e6-886f-df8292584465.png)

Unrecognized character at end of line.

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +This tutorial assumes a knowledge of other programming concepts, including:�
It sounds weird to say "This tutorial assumes a knowledge of other programming concepts, including: basic programming concepts". 

How about "This tutorial assumes knowledge of the following topics:"

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +# Getting Started using Entity Framework Core
~~using~~ with

2016-10-25 01:31 UTC, helmoski commented on content/efcore/README.md
> +This tutorial covers the basics of how to get started writing your first application using Entity Framework Core.
This tutorial covers the basics of using Entity Framework Core in a C# application.

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +## What is Entity Framework Core?
To better match the C# tutorial, let's add a chapter called "Introducing EF Core" and put this "What is Entity Framework Core?" content there. Then `getting-started/README.md` will only have the target audience, prereqs, and a table of contents. (see [C# tutorial README](https://github.com/LadyNaggaga/training-tutorials/blob/master/content/csharp/getting-started/README.md))

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +This tutorial is meant for those new or unfamiliar to EF Core, but if you already have an understanding of EF Core, consider this a refresher course. This tutorial will also help you navigate EF Core
``` markdown
This tutorial is meant as an introduction for those new to Entity Framework Core. More advanced functionality is covered in the [docs](https://docs.efproject.net/en/latest/). You should understand the following concepts before before starting this tutorial:
* C# (see the [interactive C# tutorial](https://www.microsoft.com/net/tutorials/csharp/getting-started))
* Relational Databases
```

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +If you're a new to these topics, you can check out their tutorials. If you're only a little rusty, we'll remind you of the relevant aspects along the way.
Remove

2016-10-25 01:31 UTC, helmoski commented on content/efcore/getting-started/README.md
> +Now, let's get started!
Remove

2016-10-25 22:46 UTC, helmoski commented
We decided to make significant reorganization changes, so we we will need to adjust branches and issues accordingly. Please submit a new pull request with a branch that reflects these changes.

2016-10-25 22:46 UTC, closed without merging

2016-10-26 01:08 UTC, arynhuck commented
Working on this now. Commenting as stuff is amended.

2016-10-26 01:08 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +by [The Raikes School](http://cse.unl.edu/raikes-school)
Author removed

2016-10-26 01:09 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +# Getting Started using Entity Framework Core
Fixed

2016-10-26 01:10 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +## What is Entity Framework Core?
What is Entity Framework Core? has been removed. Consider renaming this section.

2016-10-26 01:13 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +This tutorial assumes a knowledge of other programming concepts, including:�
Fixed

2016-10-26 01:13 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +This tutorial assumes a knowledge of other programming concepts, including:�
Fixed.

2016-10-26 01:21 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +This tutorial is meant for those new or unfamiliar to EF Core, but if you already have an understanding of EF Core, consider this a refresher course. This tutorial will also help you navigate EF Core
Keeping LINQ, but I used your suggested edit to cut down on the wordage.

2016-10-26 01:33 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +If you're a new to these topics, you can check out their tutorials. If you're only a little rusty, we'll remind you of the relevant aspects along the way.
Cut the database jibberish. Left LINQ.

2016-10-26 01:33 UTC, arynhuck commented on content/efcore/getting-started/README.md
> +Now, let's get started!
Done.

2016-10-26 01:35 UTC, arynhuck commented on content/efcore/README.md
> +This tutorial covers the basics of how to get started writing your first application using Entity Framework Core.
Fixed.