16 what is ef core
LadyNaggaga/training-tutorials pull request #20
Opened 2016-10-27 20:48 UTC by arynhuck

This branch contains the content that defines what EF and EF Core is (and directs the user to another reference to help them decide which one is best for their project).

Closes issue #16

2016-10-27 21:34 UTC, helmoski requested changes

2016-10-27 21:34 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +# What is Entity Framework Core?
@rdahlman3 and I had a discussion about this, and we think that "Intro to EF Core" better-matches the other chapter titles in this tutorial and the C# tutorial. For example, the C# tutorial has an "Intro to LINQ" chapter.

2016-10-27 21:34 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +Entity Framework Core (EF Core) is a lightweight, extensible, and cross-platform version of Entity Framework. Entity Framework is an object-relational mapper (O/RM) that enables .NET developers to wo
How do you feel about this flow:
1. Describe EF
2. Describe EF Core
3. Compare EF Core to EF 6.x

2016-10-27 21:34 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +As a lightweight version of the original Entity Framework, EF Core does not have all the features available in the latest version of Entity Framework (EF6.x). However, EF Core does offer a few featur
Since EF Core has some features that EF6 does not, saying "As a lightweight version..." does not work as well.

2016-10-31 20:18 UTC, rdahlman3 commented on content/efcore/getting-started/what-is-ef-core.md
> +Entity Framework Core (EF Core) is a lightweight, extensible, and cross-platform version of Entity Framework. Entity Framework is an object-relational mapper (O/RM) that enables .NET developers to wo
I'm not sure if I like that - simply because it is an intro the EF Core, starting with EF and then talking about EF Core feels weird to me.

2016-10-31 20:38 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +Entity Framework Core (EF Core) is a lightweight, extensible, and cross-platform version of Entity Framework. Entity Framework is an object-relational mapper (O/RM) that enables .NET developers to wo
Currently, we are saying that EF Core is a lightweight version of EF before even explaining what EF is.

2016-10-31 21:29 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +EF Core does not have all the features available in the latest version of Entity Framework (EF6.x). However, EF Core does offer a few features EF6.x does not. For more on these differences, check out
### Suggested Edit:

EF Core and the latest version of Entity Framework (EF6.x) differ in the features they support. A comparison of the features supported by each can be found on the [features page](https://docs.efproject.net/en/latest/efcore-vs-ef6/features.html) of the docs. If you want help determining which version is best for your project, check out [this page](https://docs.efproject.net/en/latest/efcore-vs-ef6/choosing.html) of the docs.

2016-10-31 22:05 UTC, rdahlman3 commented on content/efcore/getting-started/what-is-ef-core.md
> +Entity Framework Core (EF Core) is a lightweight, extensible, and cross-platform version of Entity Framework. Entity Framework is an object-relational mapper (O/RM) that enables .NET developers to wo
Yeah, but we then transition to say what EF is, so I like the flow better as is. @arynhuck?

2016-11-01 00:22 UTC, arynhuck commented on content/efcore/getting-started/what-is-ef-core.md
> +EF Core does not have all the features available in the latest version of Entity Framework (EF6.x). However, EF Core does offer a few features EF6.x does not. For more on these differences, check out
🌮

2016-11-01 00:27 UTC, arynhuck commented
I have made the changes. Please :shipit: : 🌮

2016-11-01 03:02 UTC, helmoski commented on content/efcore/getting-started/toc.md
> +- [Introduction to Entity Framework Core](what-is-ef-core.md)
Abbreviate Entity Framework in the table of contents please. I requested this change in PR #19 (1_getting_started_readme) as well.

2016-11-01 20:51 UTC, arynhuck commented
I want to pull in master with 1_getting_started into 16-what_is_ef_core before that is also pulled in so we can change TOC and the README.

2016-11-01 20:51 UTC, arynhuck commented on content/efcore/getting-started/toc.md
> +- [Introduction to Entity Framework Core](what-is-ef-core.md)
🌮

2016-11-01 21:10 UTC, arynhuck commented
Changes made. Master pulled in. :shipit:

2016-11-01 21:52 UTC, helmoski commented on content/efcore/getting-started/what-is-ef-core.md
> +# Intro to EF Core
Could you rename this file to be "intro-to-ef-core.md"?

2016-11-01 21:54 UTC, arynhuck commented on content/efcore/getting-started/what-is-ef-core.md
> +# Intro to EF Core
done! 🌮

2016-11-01 22:00 UTC, helmoski commented
:shipit:

2016-11-01 23:45 UTC, merged