31 - Updated querying tutorial with words instead of letters in examples
LadyNaggaga/training-tutorials pull request #32
Opened 2016-11-29 23:40 UTC by deakgeek

#31

2016-12-01 22:20 UTC, arynhuck commented
Merged master in and fixed conflicts @helmoski

2016-12-06 00:46 UTC, helmoski requested changes

2016-12-06 00:46 UTC, helmoski commented on content/efcore/getting-started/querying.md
> +        .Where(b => b.Genre == "Historical")
This should be `.Where(book => book.Genre == "Historical")` right?

2016-12-06 00:58 UTC, arynhuck commented on content/efcore/getting-started/querying.md
> +        .Where(b => b.Genre == "Historical")
Yeah, it looks like I messed up and accidentally deleted the wrong thing when resolving the conflicts. Give me a sec.

2016-12-06 21:52 UTC, helmoski commented
So, C# doesn't allow the variable in the LINQ statement to share the same name as an outer variable. Closing this PR/branch because we will stick with using the letter instead.

2016-12-06 21:52 UTC, closed without merging