34 Update LibraryContext.cs to use DbHelper to get connection string
LadyNaggaga/training-tutorials pull request #37
Opened 2016-12-06 22:27 UTC by deakgeek

#34

2016-12-06 23:01 UTC, helmoski requested changes

2016-12-06 23:01 UTC, helmoski commented on content/efcore/getting-started/samples/shared/LibraryContext.cs
> +        optionsBuilder.UseSqlite(ReplHelper<string>.DefaultConnectionString);
This isn't valid anymore.

```(C#)
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using REPLHelper;

public class LibraryContext : DbContext
{
    public DbSet<Book> Books { get; set; }
    public DbSet<Author> Authors { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite(DBHelper.GetReadonlyDbConnectionString());
    }
}
```

2016-12-06 23:01 UTC, helmoski commented on content/efcore/getting-started/samples/shared/LibraryContext.cs
> +        optionsBuilder.UseSqlite(ReplHelper<string>.DefaultConnectionString);
Please test your changes using the TestPage

2016-12-06 23:52 UTC, deakgeek commented on content/efcore/getting-started/samples/shared/LibraryContext.cs
> +        optionsBuilder.UseSqlite(ReplHelper<string>.DefaultConnectionString);
Do we need to remove the default connection string from the replhelper, then?

2016-12-07 00:24 UTC, helmoski approved these changes

2016-12-07 00:24 UTC, helmoski commented
:shipit:

2016-12-07 00:25 UTC, merged