Changing to reference reference pages
LadyNaggaga/training-tutorials pull request #57
Opened 2017-01-12 01:15 UTC by arynhuck

Take out that terrible table and add a note.

2017-01-12 01:15 UTC, arynhuck commented
🌮

2017-01-12 15:41 UTC, helmoski requested changes

2017-01-12 15:41 UTC, helmoski commented on content/efcore/getting-started/querying.md
> +> If you want to see the contents of the database or how our entities relate to each other, please refer to the [Database Reference](database-reference.md) and [Model Reference](model-reference) page
Links don't work

2017-01-19 00:35 UTC, arynhuck commented
@helmoski

2017-01-22 02:05 UTC, helmoski approved these changes

2017-01-22 02:07 UTC, merged