58 old tutorials new db
LadyNaggaga/training-tutorials pull request #59
Opened 2017-01-22 19:59 UTC by rdahlman3

Updates the old tutorials and code snippets to reflect the updated database in PR #32 in the replservice repo.

Closes #58

2017-01-23 17:07 UTC, helmoski requested changes

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +			.ThenInclude(cr => cr.Reader)
I understand why you did `cr`, but the standard would be to just do `c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +				.ThenInclude(cr => cr.Reader)
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +        .Include(cr => cr.CheckoutRecords)
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +        .Min(cr => cr.CheckoutDate);
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +We can also chain `ThenInclude` calls to include deeper layers of related data. For example, if we want to find out the reader information for the checkout records of Fredrick Douglass' books in this
For example, if we want to find out all of the readers who have checked out books written by Frederick Douglass, we will need to chain `ThenIncludes` to get the associated books, checkout records, and reader information.

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +Now, what happens if one of the properties we include also has non-primitive type properties? By default, they won't be loaded from the database, but we can tell EF Core to load them using the `ThenI
For example, we can determine all of the readers who have checked out a specific book by using `Include` to load the book's checkout records and then using `ThenInclude` to load the reader associated with each checkout record as shown below:

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +A mix of `Include` and `ThenInclude` commands can also be chained together to include related data from multiple layers across related entities. In the following example, we are looking for the autho
In the following example, we chain together `Include` and `ThenInclude` commands to load the author of _Murder on the Orient Express_, as well as all of the readers who have checked it out.

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/include-and-then-include-method-chain/Program.cs
> +                    .ThenInclude(cr => cr.Reader)
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/min-method/Program.cs
> +                .Min(cr => cr.CheckoutDate);
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method-chain/Program.cs
> +				        .ThenInclude(cr => cr.Reader)
`c`

2017-01-23 17:07 UTC, helmoski commented on content/efcore/getting-started/samples/loading-related-data/then-include-method/Program.cs
> +                    .ThenInclude(cr => cr.Reader)
`c`

2017-01-23 22:48 UTC, rdahlman3 commented on content/efcore/getting-started/loading-related-data.md
> +We can also chain `ThenInclude` calls to include deeper layers of related data. For example, if we want to find out the reader information for the checkout records of Fredrick Douglass' books in this
My b on all of these wordings - I kinda just replaced the class names without registering how it sounded, and I definitely could have done better

2017-01-23 22:57 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +We can also chain `ThenInclude` calls to include deeper layers of related data. For example, if we want to find out the reader information for the checkout records of Fredrick Douglass' books in this
No problem. It's also easier to edit the wordings after seeing what you already have, so it didn't hurt anything.

2017-01-25 22:39 UTC, helmoski requested changes

2017-01-25 22:39 UTC, helmoski commented on content/efcore/getting-started/loading-related-data.md
> +Likewise, we can find the date of the first checkout record of a book using the `Min` method:
~~...date of the first time a specific book was checked out using...~~

Actually, could we switch this to "Likewise, we can find the most recent date a specific book was checked out using the `Max` method:"

2017-01-25 22:39 UTC, helmoski commented on content/efcore/getting-started/tutorial-model-reference.md
>  In code, our entity classes look like:
Here is what the entity classes that make up our example data model look like:

2017-01-25 22:39 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
>          PublicationYear = 1818
Line 132 talks about editions and publishers still

2017-01-25 22:39 UTC, helmoski commented on content/efcore/getting-started/samples/shared/LibraryContext.cs
>  public class LibraryContext : DbContext
There is another LibraryContext.cs that needs to be updated as well:
`content\efcore\getting-started\samples\manipulating-entities\shared\LibraryContext.cs`

2017-01-25 22:46 UTC, rdahlman3 commented on content/efcore/getting-started/loading-related-data.md
> +Likewise, we can find the date of the first checkout record of a book using the `Min` method:
I like that better, makes more sense as an example

2017-01-25 22:46 UTC, rdahlman3 commented on content/efcore/getting-started/manipulating-entities.md
>          PublicationYear = 1818
balls

2017-01-26 00:42 UTC, helmoski requested changes

2017-01-26 00:42 UTC, helmoski commented on content/efcore/getting-started/samples/shared/Address.cs
> +    public String City { get; set; }
In order for the examples to work, we either need to add `using System;` or make the data type of lines 4 and 5 `string`.

2017-01-26 00:55 UTC, helmoski approved these changes

2017-01-26 00:58 UTC, merged