49 table bug fix show reference docs
LadyNaggaga/training-tutorials pull request #63
Opened 2017-01-25 22:18 UTC by rdahlman3

Adds the reference docs to the table of contents and readme so that they don't error when you try to visit. Also slightly edited the db reference doc to make it more consistent and hopefully clear, but open to suggestions on page name on both toc and the actual page

Closes #49

2017-02-06 22:49 UTC, rdahlman3 commented
@helmoski this branch is ready to be looked at now!

2017-02-06 23:38 UTC, helmoski requested changes

2017-02-06 23:38 UTC, helmoski commented on content/efcore/getting-started/tutorial-database-reference.md
> +Below are the tables and data that these tutorials work with.
Let's not say "these tutorials". Technically, all of the EF Core content is a single tutorial. Let's word it something like, "Here is the data contained within the example database used throughout this tutorial".

2017-02-06 23:38 UTC, helmoski commented on content/efcore/getting-started/tutorial-database-reference.md
> +Below are the tables and data that these tutorials work with.
Could you also update the description in the models page to say something similar?

2017-02-06 23:38 UTC, helmoski commented on content/efcore/getting-started/README.md
> +- [Appendix: Data Model Reference](tutorial-model-reference.md)
Let's put the data model reference first.

2017-02-07 00:40 UTC, helmoski requested changes

2017-02-07 00:40 UTC, helmoski commented on content/efcore/getting-started/toc.md
> +- [Appendix: Data Model Reference](tutorial-model-reference.md)
model before database

2017-02-07 00:40 UTC, helmoski commented on content/efcore/getting-started/tutorial-model-reference.md
> +This document contains class definitions of the example data models used throughout this tutorial.
It's one single data model. The entity classes make up the data model. 
Maybe, "This document contains the entity class definitions for the example data model used throughout this tutorial."

2017-02-07 00:57 UTC, merged