Defining Unique Identifiers
LadyNaggaga/training-tutorials pull request #66
Opened 2017-03-01 22:09 UTC by deakgeek

#5

2017-03-01 22:41 UTC, helmoski requested changes

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties instead. For example, we could use a book'
We say "instead" at both the beginning and end of this the first sentence. Remove one of them, please.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties instead. For example, we could use a book'
We changed the example for composite keys to use `CheckoutRecord`

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +    public string Title { get; set; }
Let's add the ISBN property in this example so it is clear that it is a property for the next section.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key/README.md
> +This code example demonstrates how EF Core sets a property as the primary key by convention.
This code example demonstrates how primary keys work in EF Core by convention.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key-fluent-api/README.md
> +# Primary Key Using Fluent API
Unconventional Key Name

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +# Composite Key Using Fluent API
Composite Key

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +This code example demonstrates how to use EF Core to set properties as a composite key using Fluent API.
This code example demonstrates how to configure a composite key in EF Core via Fluent API.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key-fluent-api/README.md
> +This code example demonstrates how to use EF Core to set a property as the primary key using Fluent API.
This code example demonstrates how to set an unconventionally-named property as the primary key in EF Core via Fluent API.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key-fluent-api/README.md
> +# Primary Key Using Fluent API
Update directory name as well

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +    public string Title { get; set; }
That way, we can also just share the same `Book` implementation for each of the unique identifier code examples.

2017-03-01 22:41 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [CheckoutRecord.cs](CheckoutRecord.cs)
This example needs `Book.cs` and `Reader.cs` to work.

2017-03-01 23:21 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties instead. For example, we could use a book'
Good catch!

2017-03-01 23:29 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [CheckoutRecord.cs](CheckoutRecord.cs)
Done

2017-03-01 23:29 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +This code example demonstrates how to use EF Core to set properties as a composite key using Fluent API.
Done

2017-03-01 23:29 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +# Composite Key Using Fluent API
Done

2017-03-01 23:29 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key-fluent-api/README.md
> +This code example demonstrates how to use EF Core to set a property as the primary key using Fluent API.
Done

2017-03-01 23:30 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key-fluent-api/README.md
> +# Primary Key Using Fluent API
Done

2017-03-01 23:30 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/primary-key/README.md
> +This code example demonstrates how EF Core sets a property as the primary key by convention.
Done

2017-03-01 23:30 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties instead. For example, we could use a book'
Done

2017-03-01 23:30 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties instead. For example, we could use a book'
Done

2017-03-01 23:31 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +    public string Title { get; set; }
Done

2017-03-02 00:40 UTC, helmoski requested changes
Need to add lesson to toc.md and readme

2017-03-02 01:02 UTC, helmoski requested changes

2017-03-02 01:02 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +	public int ISBN { get; set; }
Fix tabbing

![image](https://cloud.githubusercontent.com/assets/8516113/23488216/d04f6cb8-feb0-11e6-9db7-4a161bc07a7d.png)

2017-03-02 01:02 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +	public int ISBN { get; set; }
Use spaces instead of tabs

2017-03-02 01:02 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +		.HasKey(b => new { cr.ReaderId, cr.BookId, cr.CheckoutDate });
Add extra indent

2017-03-02 01:06 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +	public int ISBN { get; set; }
Done

2017-03-02 01:07 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +		.HasKey(b => new { cr.ReaderId, cr.BookId, cr.CheckoutDate });
Done

2017-03-02 01:17 UTC, helmoski requested changes

2017-03-02 01:17 UTC, helmoski commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties. For example, in our library data model we
2nd sentence: "Id" should be within an inline code block

2017-03-02 01:17 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [Book.cs](../../shared/Book.cs)
This implementation of `Book` requires `Author`. Use an implementation that doesn't need `Author`

2017-03-02 01:19 UTC, helmoski requested changes

2017-03-02 01:19 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [Reader.cs](../../shared/Reader.cs)
This implementation of `Reader` requires `Address`. Use an implementation that doesn't need `Address`

2017-03-06 21:42 UTC, deakgeek commented on content/efcore/getting-started/defining-unique-identifiers.md
> +Instead of adding a property to an entity solely for the purpose of uniquely identifying it, you may be able to use a combination of its existing properties. For example, in our library data model we
Done

2017-03-06 22:39 UTC, helmoski requested changes

2017-03-06 22:39 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [CheckoutRecord.cs](CheckoutRecord.cs)
This example should still have `Book.cs` and `Reader.cs`. Just use implementations that don't require `Address.cs` and `Author.cs`.

2017-03-06 22:39 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/unconventional-key-name/LibraryContext.cs
> +            .HasKey(b => new { b.ISBN });
`.HasKey(b => b.ISBN);`

2017-03-06 22:44 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/unconventional-key-name/LibraryContext.cs
> +            .HasKey(b => new { b.ISBN });
Done

2017-03-06 22:44 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/README.md
> +- [CheckoutRecord.cs](CheckoutRecord.cs)
Done

2017-03-06 22:53 UTC, helmoski requested changes

2017-03-06 22:53 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/Reader.cs
> +    public string LastName { get; set; }
Needs list of checkout records

2017-03-06 23:04 UTC, helmoski requested changes

2017-03-06 23:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/Reader.cs
> +public class Reader
Needs `using System.Collections.Generic;`

2017-03-06 23:07 UTC, deakgeek commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/Reader.cs
> +public class Reader
Done

2017-03-06 23:21 UTC, helmoski requested changes

2017-03-06 23:21 UTC, helmoski commented on content/efcore/getting-started/samples/defining-unique-identifiers/composite-key/LibraryContext.cs
> +    public DbSet<CheckoutRecord> CheckoutRecords { get; set; }
Could you add Books and Readers? EF Core detects them automatically, but I would still like them here please.

2017-03-06 23:26 UTC, helmoski approved these changes

2017-03-06 23:28 UTC, merged