8 defining entity relationships
LadyNaggaga/training-tutorials pull request #83
Opened 2017-03-07 23:18 UTC by rdahlman3

Resolves #8 

Added content and code samples for the defining entity relationships tutorial.

2017-03-07 23:20 UTC, rdahlman3 commented
Two concerns I have with this:
1) Right now, printing out the db schema doesn't really tell us much about relationships, just that (for example) there is a `ReaderId` field in the `CheckoutRecords` table, etc. It doesn't have a `ForeignKey` denotation next to the fields that are foreign keys. Not sure if that is something we want to have.

2) In the last example, we are primarily showing the many-to-many relationship, which would only include the Reader, CheckoutRecord, and Book table. However, we also include the Author and Address table in the entities, since we added those in previous examples. Do we want to still have those tables/fields, as that is how it would be if we assumed each example is building on previous examples, or do we just want to have the three tables that are relevant to the particular example we are discussing?

2017-03-08 21:43 UTC, helmoski commented
@rdahlman3 
In reference to your concerns:

1. Yes, that is something we would like, but that is a feature that will need to be implemented in REPLService, so this PR can continue without it.
2. Let's not have them build on eachother. Remove Author and Address tables please.

2017-03-08 21:55 UTC, rdahlman3 commented
@helmoski I will create a Trello card and GitHub issue for the first comment, and we can work on that next release. I will update the PR to reflect the changes for the second comment!

2017-03-08 22:04 UTC, helmoski requested changes

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/many-to-many-relationship/README.md
> +- [LibraryContext.cs](LibraryContext.cs)
Make `LibraryContext.cs` the second item in the list so that it is one of the first files to appear in the console.

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-many-relationship/README.md
> +This code example demonstrates how to create a one-to-many relationship using navigation properties.
... relationship *in EF Core* using ...

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-many-relationship/README.md
> +- [LibraryContext.cs](LibraryContext.cs)
Make `LibraryContext.cs` the second item in the list so that it is one of the first files to appear in the console.

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/many-to-many-relationship/README.md
> +This code example demonstrates how to create a many-to-many relationship using a joining table.
... relationship *in EF Core* using...

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-manual-foreign-key/README.md
> +This code example demonstrates how to create a one-to-one relationship by manually setting the foreign key using Fluent API.
... relationship *in EF Core* by ...

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-manual-foreign-key/README.md
> +- [LibraryContext.cs](LibraryContext.cs)
Make `LibraryContext.cs` the second item in the list so that it is one of the first files to appear in the console.

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-manual-foreign-key/README.md
> +# One-to-One Relationships with Manual Foreign Key
Relationship

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-many-relationship/README.md
> +# One-to-Many Relationships
Relationship

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/many-to-many-relationship/README.md
> +# Many-to-Many Relationships
Relationship

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-relationship/README.md
> +# One-to-One Relationships
Relationship

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-relationship/README.md
> +This code example demonstrates how to create a one-to-one relationship using a navigation property.
... relationship *in EF Core* using ~~a~~ navigation *properties*.

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-relationship/README.md
> +This code example demonstrates how to create a one-to-one relationship using a navigation property.
If you can't tell, "a" is crossed out above

2017-03-08 22:04 UTC, helmoski commented on content/efcore/getting-started/samples/defining-entity-relationships/one-to-one-relationship/README.md
> +- [LibraryContext.cs](LibraryContext.cs)
Make `LibraryContext.cs` the second item in the list so that it is one of the first files to appear in the console.

2017-03-09 01:43 UTC, helmoski approved these changes

2017-03-09 01:44 UTC, merged