Update manipulating entities tutorial with cascade delete
LadyNaggaga/training-tutorials pull request #99
Opened 2017-04-10 23:27 UTC by deakgeek

#98

2017-04-11 19:17 UTC, helmoski requested changes

2017-04-11 19:17 UTC, helmoski commented on content/efcore/getting-started/manipulating-entities.md
> +In the previous example, we were able to successfully delete a book, but what happened to that book's checkout records? The short answer is it depends. The way that EF Core handles deletion of an ent
Add quotes around cascade delete docs page name

2017-04-11 21:42 UTC, arynhuck commented on content/efcore/getting-started/manipulating-entities.md
> +In the previous example, we were able to successfully delete a book, but what happened to that book's checkout records? The short answer is it depends. The way that EF Core handles deletion of an ent
🌮

2017-04-11 21:42 UTC, arynhuck commented
:shipit: ?

2017-04-12 22:04 UTC, arynhuck commented
@helmoski :shipit: :shipit: :shipit:

2017-04-15 03:00 UTC, helmoski approved these changes

2017-04-15 03:01 UTC, merged